# 解析器配置
#
# 注：在 windows 平台下使用 youtube-dl 解析器时，从 chrome, edge 等浏览器获取 cookie 有可能会失败，换成 firefox 即可
decoder:
  use: cat-catch:tx # 使用哪种解析方式，可选值：none, youtube-dl, cat-catch:tx
  max-retry: 5 # 最大的尝试解析次数
  youtube-dl: # youtube-dl 解析器相关配置
    cookies-from: chrome # 从哪个浏览器获取 cookie，推荐 firefox，该参数会直接传递给 youtube-dl，传入 none 则忽略
    format-codes: # 下载视频的编码，可传多个，按照顺序进行解析，两种格式：'视频编码+音频编码' 或者 '视频编码'，只会下载首次解析成功的格式，可以不传此参数，在程序执行时手动选择
    remember-format: -1 # 是否记住视频格式，程序自动根据 host 进行区分，每次启动程序时缓存都会重置，可选值：-1, 1
  cat-catch: # 猫抓解析器
    headless: 1 # 是否开启无头模式, 可选值: -1, 1
    sites: # 针对不同的网站分别实现猫抓解析器
      tx:
        cookie-json-path: cookie-files/tx.json # Cookie 文件绝对路径
        video-format: fhd # 视频格式, 可选值: sd, hd, shd, fhd, uhd, hdr10

# 下载器配置
downloader:
  use: multi-thread # 要使用哪个下载器，可选值：simple, multi-thread
  task-thread-count: 2 # 处理下载任务的线程个数
  dl-thread-count: 12 # 多线程下载的线程个数
  download-dir: /Users/ambitious/Downloads # 视频文件下载位置
  # download-dir: C:/Users/Ambitious/Downloads # 视频文件下载位置
  ts-dir-suffix: temp_ts_files # 暂存 ts 文件的目录后缀
  rate-limit: 10mbps # 下载限速，两种单位可选：mbps, kbps，-1 则不限速

# ts 转换器配置
#
# 对于不同的 m3u8, 有的转换器合并后的视频文件会有跳帧问题，可以尝试更换转换器
transfer:
  use: ffmpeg_str_v2 # 要选用哪个转码器，可选值：ffmpeg_str, ffmpeg_txt, ffmpeg_str_v2
  ts-filename-regex: _(\d+)\. # 正则表达式，用于匹配出 ts 文件的序号

# 针对不同的域名进行定制化配置
# 
# 针对 decoder 进行定制化配置
# 可配置的属性：use, resource-type, youtube-dl.cookies-from, youtube-dl.format-codes, youtube-dl.remember-format
#
# 针对 transfer 进行定制化配置
# 可配置的属性：use
customs:
  - decoder: 
      use: youtube-dl
      youtube-dl:
        cookies-from: chrome
        format-codes:
        remember-format: 1
    hosts: # 对哪些域名生效，必须配置完整，有端口也要加上
      - www.mgtv.com
      - www.youtube.com
      - www.bilibili.com
  - decoder:
      use: none
    hosts:
      - apd-vlive.apdcdn.tc.qq.com
      - pcvideoaliyun.titan.mgtv.com
      - pcvideotx.titan.mgtv.com